### ISSUE TITLE
New Feature Documentation

### ISSUE THREAD

**Issue by micgro42** [splitbrain/dokuwiki#2299]
The merged pull requests have to be documented: 

- [x] better core search #2286 
- [x] manifest.json for PWA functionality #2241 
- [x] CLI Plugins #2168 
- [x] `JSINFO` is now also available in detail.php and mediamanager.php and `DOKU_UNC` and `DOKU_UNH` are deprecated #2190

**Comment by splitbrain** [comment]
https://www.dokuwiki.org/devel:cli_plugins

**Comment by micgro42** [comment]
* https://www.dokuwiki.org/devel:manifest
* https://www.dokuwiki.org/devel:event:manifest_send

**Comment by splitbrain** [comment]
The new search config options aren't documented, yet:

* https://www.dokuwiki.org/config:search_limit_to_first_ns
* https://www.dokuwiki.org/config:search_default_fragment_behaviour
